### PR TITLE
docs: revise OAS

### PR DESCRIPTION
**Pull request by inventarSarah**
This branch contains the edited API documentation (OAS).

I've used the openapitools/openapi-diff tool to test backward compatibility and make sure my changes to the OAS do not introduce breaking changes -> Test was successful, changes are backward compatible.

Note: I use a YAML tool in my IDE, which is why the format of the yaml is sometimes different than before. 
So, when you review the changes directly in the file on GitHub, make sure to have "Ignore Whitespaces" activated in the top right corner. That way, you can compare changes per line instead of blocks.

A summary of the changes:
- fix spelling mistakes and the likes
- check consistency
- make sure we favor present tense and active voice
- add links to external documentation where it makes sense (eg. ISO naming standards for locations)
- simplify some sentences while ensuring to not lose information
- add missing Schema descriptions for consistency 
- add short example descriptions to Create Measurement endpoint examples

### CODE REVIEW

**Comment by MartinKolarik** [comment]
@inventarSarah I see it's marked as a draft, are you working on any more changes or should I review now?

**Comment by inventarSarah** [comment]
@MartinKolarik I needed to fix something but it's ready now!

**Comment by MartinKolarik** [comment]
@inventarSarah thanks, I reviewed everything and made some additional modifications, mostly removing a few descriptions that would be repetitive in the rendered docs (which isn't entirely obvious when looking at the YAML version) and tweaking the wording in some cases...

Can you please recheck for obvious errors like spelling, missing words, etc, but don't make any additional changes? If you find any, keep the diff as clean as possible so that I can review it easily, or use GitHub's suggestions feature here in the "Files changed" tab:
https://dl.dropboxusercontent.com/scl/fi/6t40uipia5p0hngl94t50/2024-01-30_18-12-09.png?rlkey=g8utd668x6crtsci7ufs6zdt2&dl=0

**Comment by MartinKolarik** [comment]
I'm going to merge this. If you have any additional suggestions based on my previous comment, feel free to follow up in a new PR.

**Pull request merged**
